# Generated by Django 5.2.17 on 2026-09-25 06:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
import webhooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "url",
                    models.URLField(
                        max_length=1000,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                        verbose_name="URL",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        default=webhooks.models.generate_secret,
                        help_text="Requests are signed with this value. Give it to the receiving application so it can check that a request came from here.",
                        max_length=255,
                        verbose_name="Secret",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "last_delivery",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last delivery"
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook endpoint",
                "verbose_name_plural": "Webhook endpoints",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Sent with every attempt so the receiving application can discard a repeat. It is in the body too, and that copy is the one covered by the signature.",
                        unique=True,
                        verbose_name="Event ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text='The kind of change, e.g. "feeding.created".',
                        max_length=255,
                        verbose_name="Type",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(max_length=255, verbose_name="Object ID"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Attempts"),
                ),
                (
                    "next_attempt",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Empty once the attempts are used up: the event stays as a record and is not tried again.",
                        null=True,
                        verbose_name="Next attempt",
                    ),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Last error"
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook event",
                "verbose_name_plural": "Webhook events",
                "ordering": ("-created",),
            },
        ),
    ]
