tasks:
  - init: >
      sudo apt update &&
      sudo apt -y install gettext &&
      pipenv install --three &&
      npm install -g gulp-cli &&
      npm install &&
      gulp migrate
    env:
      DJANGO_SETTINGS_MODULE: babybuddy.settings.gitpod
    command: gulp

ports:
  - port: 8000
