tasks:
  - init: >
      sudo apt update &&
      sudo apt -y install gettext &&
      pip install uv &&
      uv sync &&
      npm install -g gulp-cli &&
      npm install &&
      gulp migrate
    env:
      DJANGO_SETTINGS_MODULE: babybuddy.settings.gitpod
      BB_PORT: "8282"
    command: gulp

ports:
  - port: 8282
