# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 16:57
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timer",
            name="start",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Start Time"
            ),
        ),
    ]
