# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 09:00
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="child/picture/"),
        ),
    ]
