# Generated by Django 3.0.2 on 2020-01-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_auto_20190607_1422"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaperchange",
            name="amount",
            field=models.FloatField(blank=True, null=True, verbose_name="Amount"),
        ),
    ]
