# Generated by Django 3.0.2 on 2020-01-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_diaperchange_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="timer",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timers",
                to="core.Child",
                verbose_name="Child",
            ),
        ),
    ]
