# Generated by Django 2.2.1 on 2019-06-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190916_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='method',
            field=models.CharField(choices=[('bottle', 'Bottle'), ('left breast', 'Left Breast'), ('right breast', 'Right Breast'), ('both breasts', 'Both Breasts'), ('spoon', 'Spoon'), ('other', 'Other')],  max_length=255, verbose_name='method'),
        ),
    ]
