# Generated by Django 3.1 on 2020-08-13 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_auto_20200214_1939"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Time"
            ),
        ),
    ]
