# Generated by Django 3.2.5 on 2021-07-26 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_music'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'ordering': ['-time'], 'verbose_name': 'Music', 'verbose_name_plural': 'Music'},
        ),
        migrations.RemoveField(
            model_name='music',
            name='date',
        ),
        migrations.RemoveField(
            model_name='music',
            name='disliked_song',
        ),
        migrations.AddField(
            model_name='music',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
