# Generated by Django 3.2.5 on 2021-07-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210726_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=255, verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.CharField(max_length=255, verbose_name='Song'),
        ),
    ]
