# Generated by Django 4.0.3 on 2022-03-08 12:42

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_tag_tagged_note_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmi",
            name="tags",
            field=core.models.TaggableManager(
                blank=True,
                help_text="Click on the tags to add (+) or remove (-) tags or use the text editor to create new tags.",
                through="core.Tagged",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="diaperchange",
            name="tags",
            field=core.models.TaggableManager(
                blank=True,
                help_text="Click on the tags to add (+) or remove (-) tags or use the text editor to create new tags.",
                through="core.Tagged",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="feeding",
            name="tags",
            field=core.models.TaggableManager(
                blank=True,
                help_text="Click on the tags to add (+) or remove (-) tags or use the text editor to create new tags.",
                through="core.Tagged",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="headcircumference",
            name="tags",
            field=core.models.TaggableManager(
                blank=True,
                help_text="Click on the tags to add (+) or remove (-) tags or use the text editor to create new tags.",
                through="core.Tagged",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="height",
            name="tags",
            field=core.models.TaggableManager(
                blank=True,
                help_text="Click on the tags to add (+) or remove (-) tags or use the text editor to create new tags.",
                through="core.Tagged",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="sleep",
            name="tags",
            field=core.models.TaggableManager(
                blank=True,
                help_text="Click on the tags to add (+) or remove (-) tags or use the text editor to create new tags.",
                through="core.Tagged",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="temperature",
            name="tags",
            field=core.models.TaggableManager(
                blank=True,
                help_text="Click on the tags to add (+) or remove (-) tags or use the text editor to create new tags.",
                through="core.Tagged",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="tummytime",
            name="tags",
            field=core.models.TaggableManager(
                blank=True,
                help_text="Click on the tags to add (+) or remove (-) tags or use the text editor to create new tags.",
                through="core.Tagged",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="weight",
            name="tags",
            field=core.models.TaggableManager(
                blank=True,
                help_text="Click on the tags to add (+) or remove (-) tags or use the text editor to create new tags.",
                through="core.Tagged",
                to="core.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
