# Generated by Django 4.0.3 on 2022-03-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pumping'),
        ('core', '0020_bmi_tags_diaperchange_tags_feeding_tags_and_more'),
    ]

    operations = [
    ]
