# Generated by Django 4.0.4 on 2022-04-12 02:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_pumping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmi",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="diaperchange",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="Time"
            ),
        ),
        migrations.AlterField(
            model_name="headcircumference",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="height",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="Time"
            ),
        ),
        migrations.AlterField(
            model_name="temperature",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="Time"
            ),
        ),
        migrations.AlterField(
            model_name="weight",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Date"
            ),
        ),
    ]
