# Generated by Django 4.0.2 on 2022-02-13 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_babybuddytag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='babybuddytag',
            name='last_used',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
