# Generated by Django 4.0.2 on 2022-02-14 15:50

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_babybuddytag_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.BabyBuddyTagged', to='core.BabyBuddyTag', verbose_name='Tags'),
        ),
    ]
