# Generated by Django 4.1.3 on 2022-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="timer",
            name="context",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="Context"
            ),
        ),
    ]
