# Generated by Django 4.0.4 on 2022-06-10 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_pumping_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeding",
            name="end",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="End time"
            ),
        ),
        migrations.AlterField(
            model_name="feeding",
            name="start",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="Start time"
            ),
        ),
        migrations.AlterField(
            model_name="pumping",
            name="time",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="Time"
            ),
        ),
        migrations.AlterField(
            model_name="sleep",
            name="end",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="End time"
            ),
        ),
        migrations.AlterField(
            model_name="sleep",
            name="start",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="Start time"
            ),
        ),
        migrations.AlterField(
            model_name="tummytime",
            name="end",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="End time"
            ),
        ),
        migrations.AlterField(
            model_name="tummytime",
            name="start",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="Start time"
            ),
        ),
    ]
