# Generated by Django 4.2 on 2023-05-07 00:28

from django.db import migrations, models
from django.utils import timezone


def set_sleep_nap_values(apps, schema_editor):
    # Use apps.get_model for the historical model — the live core.models.Sleep
    # has SyncTimestampMixin whose save() writes sync_updated_at, a column that
    # doesn't exist yet in a from-scratch migration chain. The historical model
    # only has fields from the migration state at this point, so its save() is
    # Django's default and won't reference sync_updated_at.
    Sleep = apps.get_model("core", "Sleep")

    for sleep in Sleep.objects.all():
        sleep.nap = False
        sleep.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_timer_options_remove_timer_duration_and_more"),
        ("dbsettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sleep",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-start"],
                "permissions": [("can_edit_sleep_settings", "Can edit Sleep settings")],
                "verbose_name": "Sleep",
                "verbose_name_plural": "Sleep",
            },
        ),
        migrations.RemoveField(
            model_name="sleep",
            name="napping",
        ),
        migrations.AddField(
            model_name="sleep",
            name="nap",
            field=models.BooleanField(null=True, verbose_name="Nap"),
        ),
        migrations.RunPython(
            set_sleep_nap_values, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="sleep",
            name="nap",
            field=models.BooleanField(blank=True, verbose_name="Nap"),
        ),
    ]
