# Generated by Django 4.2.5 on 2023-10-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_weightpercentile_weightpercentile_unique_age_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="notes/images/", verbose_name="Image"
            ),
        ),
    ]
