# Generated by Django 4.2.6 on 2023-10-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_note_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="birth_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Birth time"),
        ),
    ]
