# Generated by Django 5.0.6 on 2024-05-13 02:38

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_heightpercentile_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": [django.db.models.functions.text.Lower("name")],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
