# Generated by Django 5.0.6 on 2024-06-03 10:45

import core.models
import django_enumfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_alter_tag_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="number_of_naps",
            field=django_enumfield.db.fields.EnumField(
                default=1, enum=core.models.Child.NumberOfNaps
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="wake_window",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Wake Window"
            ),
        ),
    ]
