# Generated by Django 5.1.4 on 2024-12-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_recalculate_durations'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='solid_food_choice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Solid Food Choice'),
        ),
    ]
