# Generated by Django 5.2.17 on 2026-08-28 13:41

import core.models
import core.utils
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_medication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='The name of the activity, e.g. "Bath" or "Walk".',
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("activities", "Activities"),
                            ("bmi", "BMI"),
                            ("calendar", "Calendar"),
                            ("camera", "Camera"),
                            ("chat", "Chat"),
                            ("child", "Child"),
                            ("clock", "Clock"),
                            ("dashboard", "Dashboard"),
                            ("diaperchange", "Diaper Change"),
                            ("feeding", "Feeding"),
                            ("graph", "Graph"),
                            ("head-circumference", "Head Circumference"),
                            ("height", "Height"),
                            ("list", "List"),
                            ("lock", "Lock"),
                            ("mail", "Mail"),
                            ("measurements", "Measurements"),
                            ("medication", "Medication"),
                            ("note", "Note"),
                            ("pumping", "Pumping"),
                            ("refresh", "Refresh"),
                            ("sad", "Sad"),
                            ("sleep", "Sleep"),
                            ("source", "Source"),
                            ("stop", "Stop"),
                            ("tag", "Tag"),
                            ("temperature", "Temperature"),
                            ("timeline", "Timeline"),
                            ("timer", "Timer"),
                            ("today", "Today"),
                            ("tummytime", "Tummy Time"),
                            ("user", "User"),
                            ("weight", "Weight"),
                        ],
                        default="activities",
                        max_length=64,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="An emoji to use in place of the icon, e.g. 🛁 or 🚶. Leave blank to use the icon.",
                        max_length=8,
                        verbose_name="Emoji",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default=core.utils.random_color,
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator("^#[0-9a-fA-F]{6}$")
                        ],
                        verbose_name="Color",
                    ),
                ),
                (
                    "has_duration",
                    models.BooleanField(
                        default=False,
                        help_text="Record a start and end time for this activity. Otherwise only a single point in time is recorded.",
                        verbose_name="Track duration",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive activities are hidden from add menus and dashboards but their existing entries are kept.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Activities are sorted by this value, then by name.",
                        verbose_name="Sort order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Type",
                "verbose_name_plural": "Activity Types",
                "ordering": ["order", django.db.models.functions.text.Lower("name")],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime,
                        verbose_name="Start time",
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="End time"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        editable=False, null=True, verbose_name="Duration"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "tags",
                    core.models.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="core.Tagged",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.activitytype",
                        verbose_name="Activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["-start"],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
    ]
