# Generated by Django 5.2.15 on 2026-07-31

import core.models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_medication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fruit", "Fruit"),
                            ("vegetable", "Vegetable"),
                            ("meat", "Meat"),
                            ("fish", "Fish"),
                            ("egg", "Egg"),
                            ("dairy", "Dairy"),
                            ("cereal", "Cereal"),
                            ("legume", "Legume"),
                            ("nuts", "Nuts"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        verbose_name="Category",
                    ),
                ),
                (
                    "allergen",
                    models.BooleanField(default=False, verbose_name="Allergen"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Active"),
                ),
            ],
            options={
                "verbose_name": "Food",
                "verbose_name_plural": "Foods",
                "ordering": [django.db.models.functions.text.Lower("name")],
                "default_permissions": ("view", "add", "change", "delete"),
                "indexes": [
                    models.Index(
                        fields=["active", "category"],
                        name="core_food_active_cat_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="core_food_name_ci_unique",
                        violation_error_message=(
                            "A food with this name already exists."
                        ),
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime,
                        verbose_name="Time",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("morning snack", "Morning snack"),
                            ("lunch", "Lunch"),
                            ("afternoon snack", "Afternoon snack"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        verbose_name="Meal type",
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not specified"),
                            ("tasted", "Tasted only"),
                            ("little", "A little"),
                            ("normal", "Normal"),
                            ("plenty", "Plenty"),
                            ("all", "All"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="Approximate quantity",
                    ),
                ),
                (
                    "preparation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("blended", "Blended"),
                            ("puree", "Puree"),
                            ("pieces", "Pieces"),
                            ("baby-led weaning", "Baby-led weaning (BLW)"),
                            ("liquid", "Liquid"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        verbose_name="Preparation",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "tags",
                    core.models.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="core.Tagged",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal",
                "verbose_name_plural": "Meals",
                "ordering": ["-time", "-id"],
                "default_permissions": ("view", "add", "change", "delete"),
                "indexes": [
                    models.Index(
                        fields=["child", "-time"],
                        name="core_meal_child_time_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChildFoodProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taste",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not rated"),
                            ("likes very much", "Likes very much"),
                            ("likes", "Likes"),
                            ("indifferent", "Indifferent"),
                            ("dislikes", "Dislikes"),
                            ("dislikes very much", "Dislikes very much"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="Taste",
                    ),
                ),
                (
                    "tolerance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not rated"),
                            ("well tolerated", "Well tolerated"),
                            ("poorly tolerated", "Poorly tolerated"),
                            ("possible allergy", "Possible allergy"),
                            ("confirmed allergy", "Confirmed allergy"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="Tolerance",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_profiles",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_profiles",
                        to="core.food",
                        verbose_name="Food",
                    ),
                ),
            ],
            options={
                "verbose_name": "Child food profile",
                "verbose_name_plural": "Child food profiles",
                "ordering": ["child", "food__name"],
                "default_permissions": ("view", "add", "change", "delete"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child", "food"),
                        name="core_child_food_profile_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MealFood",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.food",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.meal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal food",
                "verbose_name_plural": "Meal foods",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("meal", "food"),
                        name="core_meal_food_unique",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="meal",
            name="foods",
            field=models.ManyToManyField(
                related_name="meals",
                through="core.MealFood",
                to="core.food",
                verbose_name="Foods",
            ),
        ),
    ]
