# Generated by Django 5.2.15 on 2026-06-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_medication"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text=(
                    "Estimated due date. When set and later than the birth "
                    "date (i.e. the child was born preterm), growth percentiles "
                    "are plotted against corrected age."
                ),
                null=True,
                verbose_name="Due date",
            ),
        ),
    ]
