# Generated by Django 5.1.15 on 2026-02-14 20:33

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_medication_amount_unit_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expirable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g. Formula, Breast milk, Pedialyte.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime,
                        verbose_name="Opened at",
                    ),
                ),
                (
                    "expiry_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Number of days after opening before the item should be discarded.",
                        verbose_name="Expires after (days)",
                    ),
                ),
                (
                    "discarded",
                    models.BooleanField(default=False, verbose_name="Discarded"),
                ),
                (
                    "discarded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Discarded at"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expirables",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "tags",
                    core.models.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="core.Tagged",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expirable",
                "verbose_name_plural": "Expirables",
                "ordering": ["-time"],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
    ]
