apiVersion: v1
kind: Service
metadata:
  name: babybuddy-db
spec:
  ports:
    - port: 5432
  selector:
    app: babybuddy-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: babybuddy-db
spec:
  serviceName: "babybuddy-db"
  replicas: 1
  selector:
    matchLabels:
      app: babybuddy-db
  template:
    metadata:
      labels:
        app: babybuddy-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: babybuddy-config
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: babybuddy-config
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: babybuddy-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi