# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("pumping/", views.PumpingList.as_view(), name="pumping-list"),
    path("pumping/add/", views.PumpingAdd.as_view(), name="pumping-add"),
    path(
        "pumping/<int:pk>/",
        views.PumpingUpdate.as_view(),
        name="pumping-update",
    ),
    path(
        "pumping/<int:pk>/delete/",
        views.PumpingDelete.as_view(),
        name="pumping-delete",
    ),
    path("children/", views.ChildList.as_view(), name="child-list"),
    path("children/add/", views.ChildAdd.as_view(), name="child-add"),
    path("children/<str:slug>/", views.ChildDetail.as_view(), name="child"),
    path("children/<str:slug>/edit/", views.ChildUpdate.as_view(), name="child-update"),
    path(
        "children/<str:slug>/delete/", views.ChildDelete.as_view(), name="child-delete"
    ),
    path("timeline/", views.Timeline.as_view(), name="timeline"),
    path("visit-summary/", views.ActivityReport.as_view(), name="visit-summary"),
    path("changes/", views.DiaperChangeList.as_view(), name="diaperchange-list"),
    path("changes/add/", views.DiaperChangeAdd.as_view(), name="diaperchange-add"),
    path(
        "changes/<int:pk>/",
        views.DiaperChangeUpdate.as_view(),
        name="diaperchange-update",
    ),
    path(
        "changes/<int:pk>/delete/",
        views.DiaperChangeDelete.as_view(),
        name="diaperchange-delete",
    ),
    path(
        "feedings/bottle/add/",
        views.BottleFeedingAdd.as_view(),
        name="bottle-feeding-add",
    ),
    path(
        "feedings/breast/add/",
        views.BreastFeedingAdd.as_view(),
        name="breast-feeding-add",
    ),
    path(
        "feedings/solid/add/",
        views.SolidFeedingAdd.as_view(),
        name="solid-feeding-add",
    ),
    path("feedings/", views.FeedingList.as_view(), name="feeding-list"),
    path("feedings/add/", views.FeedingAdd.as_view(), name="feeding-add"),
    path("feedings/<int:pk>/", views.FeedingUpdate.as_view(), name="feeding-update"),
    path(
        "feedings/<int:pk>/delete/",
        views.FeedingDelete.as_view(),
        name="feeding-delete",
    ),
    path("notes/", views.NoteList.as_view(), name="note-list"),
    path("notes/add/", views.NoteAdd.as_view(), name="note-add"),
    path("notes/<int:pk>/", views.NoteUpdate.as_view(), name="note-update"),
    path("notes/<int:pk>/delete/", views.NoteDelete.as_view(), name="note-delete"),
    path("sleep/", views.SleepList.as_view(), name="sleep-list"),
    path("sleep/add/", views.SleepAdd.as_view(), name="sleep-add"),
    path("sleep/<int:pk>/", views.SleepUpdate.as_view(), name="sleep-update"),
    path("sleep/<int:pk>/delete/", views.SleepDelete.as_view(), name="sleep-delete"),
    path("temperature/", views.TemperatureList.as_view(), name="temperature-list"),
    path("temperature/add/", views.TemperatureAdd.as_view(), name="temperature-add"),
    path(
        "temperature/<int:pk>/",
        views.TemperatureUpdate.as_view(),
        name="temperature-update",
    ),
    path(
        "temperature/<int:pk>/delete/",
        views.TemperatureDelete.as_view(),
        name="temperature-delete",
    ),
    path("tags/", views.TagAdminList.as_view(), name="tag-list"),
    path("tags/add/", views.TagAdminAdd.as_view(), name="tag-add"),
    path("tags/<str:slug>/", views.TagAdminDetail.as_view(), name="tag-detail"),
    path("tags/<str:slug>/edit", views.TagAdminUpdate.as_view(), name="tag-update"),
    path("tags/<str:slug>/delete/", views.TagAdminDelete.as_view(), name="tag-delete"),
    path("timers/", views.TimerList.as_view(), name="timer-list"),
    path("timers/add/", views.TimerAdd.as_view(), name="timer-add"),
    path("timers/add/quick/", views.TimerAddQuick.as_view(), name="timer-add-quick"),
    path("timers/<int:pk>/", views.TimerDetail.as_view(), name="timer-detail"),
    path("timers/<int:pk>/edit/", views.TimerUpdate.as_view(), name="timer-update"),
    path("timers/<int:pk>/delete/", views.TimerDelete.as_view(), name="timer-delete"),
    path(
        "timers/<int:pk>/restart/", views.TimerRestart.as_view(), name="timer-restart"
    ),
    path("tummy-time/", views.TummyTimeList.as_view(), name="tummytime-list"),
    path("tummy-time/add/", views.TummyTimeAdd.as_view(), name="tummytime-add"),
    path(
        "tummy-time/<int:pk>/", views.TummyTimeUpdate.as_view(), name="tummytime-update"
    ),
    path(
        "tummy-time/<int:pk>/delete/",
        views.TummyTimeDelete.as_view(),
        name="tummytime-delete",
    ),
    path("weight/", views.WeightList.as_view(), name="weight-list"),
    path("weight/add/", views.WeightAdd.as_view(), name="weight-add"),
    path("weight/<int:pk>/", views.WeightUpdate.as_view(), name="weight-update"),
    path("weight/<int:pk>/delete/", views.WeightDelete.as_view(), name="weight-delete"),
    path("height/", views.HeightList.as_view(), name="height-list"),
    path("height/add/", views.HeightAdd.as_view(), name="height-add"),
    path("height/<int:pk>/", views.HeightUpdate.as_view(), name="height-update"),
    path("height/<int:pk>/delete/", views.HeightDelete.as_view(), name="height-delete"),
    path("medication/", views.MedicationList.as_view(), name="medication-list"),
    path("medication/add/", views.MedicationAdd.as_view(), name="medication-add"),
    path(
        "medication/<int:pk>/",
        views.MedicationUpdate.as_view(),
        name="medication-update",
    ),
    path(
        "medication/<int:pk>/delete/",
        views.MedicationDelete.as_view(),
        name="medication-delete",
    ),
    path(
        "head-circumference/",
        views.HeadCircumferenceList.as_view(),
        name="head-circumference-list",
    ),
    path(
        "head-circumference/add/",
        views.HeadCircumferenceAdd.as_view(),
        name="head-circumference-add",
    ),
    path(
        "head-circumference/<int:pk>/",
        views.HeadCircumferenceUpdate.as_view(),
        name="head-circumference-update",
    ),
    path(
        "head-circumference/<int:pk>/delete/",
        views.HeadCircumferenceDelete.as_view(),
        name="head-circumference-delete",
    ),
    path("bmi/", views.BMIList.as_view(), name="bmi-list"),
    path("bmi/add/", views.BMIAdd.as_view(), name="bmi-add"),
    path("bmi/<int:pk>/", views.BMIUpdate.as_view(), name="bmi-update"),
    path("bmi/<int:pk>/delete/", views.BMIDelete.as_view(), name="bmi-delete"),

    path("supplies/recalculate/", views.SupplyItemRecalculate.as_view(), name="supplyitem-recalculate"),
    path(
        "supplies/<int:pk>/retire/",
        views.SupplyItemRetire.as_view(),
        name="supplyitem-retire",
    ),
    path("supplies/", views.SupplyItemList.as_view(), name="supplyitem-list"),
    path("wipes/", views.WipesListView.as_view(), name="wipes-list"),
    path("supplies/add/", views.SupplyItemAdd.as_view(), name="supplyitem-add"),
    path("supplies/<int:pk>/", views.SupplyItemUpdate.as_view(), name="supplyitem-update"),
    path("supplies/<int:pk>/delete/", views.SupplyItemDelete.as_view(), name="supplyitem-delete"),

    path("products/", views.ProductLineList.as_view(), name="productline-list"),
    path("products/add/", views.ProductLineAdd.as_view(), name="productline-add"),
    path("products/<int:pk>/", views.ProductLineUpdate.as_view(), name="productline-update"),
    path("products/<int:pk>/delete/", views.ProductLineDelete.as_view(), name="productline-delete"),

    path("spit-up/", views.SpitUpList.as_view(), name="spitup-list"),
    path("spit-up/add/", views.SpitUpAdd.as_view(), name="spitup-add"),
    path("spit-up/<int:pk>/", views.SpitUpUpdate.as_view(), name="spitup-update"),
    path("spit-up/<int:pk>/delete/", views.SpitUpDelete.as_view(), name="spitup-delete"),
    path("equipment/", views.EquipmentItemList.as_view(), name="equipment-list"),
    path("equipment/add/", views.EquipmentItemAdd.as_view(), name="equipment-add"),
    path("equipment/<int:pk>/", views.EquipmentItemUpdate.as_view(), name="equipment-update"),
    path("equipment/<int:pk>/delete/", views.EquipmentItemDelete.as_view(), name="equipment-delete"),

    path("feed-inventory/", views.FeedInventoryList.as_view(), name="feedinventory-list"),
    path("feed-inventory/add/", views.FeedInventoryAdd.as_view(), name="feedinventory-add"),
    path("feed-inventory/<int:pk>/", views.FeedInventoryUpdate.as_view(), name="feedinventory-update"),
    path("feed-inventory/<int:pk>/delete/", views.FeedInventoryDelete.as_view(), name="feedinventory-delete"),
    path("feed-inventory/<int:pk>/consume/", views.FeedInventoryConsume.as_view(), name="feedinventory-consume"),
    path("feed-inventory/<int:pk>/discard/", views.FeedInventoryDiscard.as_view(), name="feedinventory-discard"),
    path("feed-inventory/<int:pk>/combine/", views.FeedInventoryCombine.as_view(), name="feedinventory-combine"),
    path("feed-inventory/<int:pk>/combine-into/", views.FeedInventoryCombineInto.as_view(), name="feedinventory-combine-into"),
    path("feed-inventory/<int:pk>/split/", views.FeedInventorySplit.as_view(), name="feedinventory-split"),
    path("feed-inventory/<int:pk>/warm/", views.FeedInventoryWarm.as_view(), name="feedinventory-warm"),

    path("formula-stock/", views.FormulaStockList.as_view(), name="formulastock-list"),
    path("formula-stock/add/", views.FormulaStockAdd.as_view(), name="formulastock-add"),
    path("formula-stock/<int:pk>/", views.FormulaStockUpdate.as_view(), name="formulastock-update"),
    path("formula-stock/<int:pk>/delete/", views.FormulaStockDelete.as_view(), name="formulastock-delete"),
    path("formula-stock/<int:pk>/open/", views.FormulaStockOpen.as_view(), name="formulastock-open"),
    path("formula-stock/<int:pk>/adjust/", views.FormulaStockAdjust.as_view(), name="formulastock-adjust"),
    path("prepared-feeds/", views.PreparedFeedList.as_view(), name="preparedfeed-list"),
    path("prepared-feeds/add/", views.PreparedFeedAdd.as_view(), name="preparedfeed-add"),
    path("prepared-feeds/<int:pk>/", views.PreparedFeedUpdate.as_view(), name="preparedfeed-update"),
    path("prepared-feeds/<int:pk>/delete/", views.PreparedFeedDelete.as_view(), name="preparedfeed-delete"),
    path("doctor-visits/", views.DoctorVisitList.as_view(), name="doctorvisit-list"),
    path("doctor-visits/add/", views.DoctorVisitAdd.as_view(), name="doctorvisit-add"),
    path(
        "doctor-visits/<int:pk>/",
        views.DoctorVisitUpdate.as_view(),
        name="doctorvisit-update",
    ),
    path(
        "doctor-visits/<int:pk>/delete/",
        views.DoctorVisitDelete.as_view(),
        name="doctorvisit-delete",
    ),
    path("prescriptions/", views.PrescriptionList.as_view(), name="prescription-list"),
    path("prescriptions/add/", views.PrescriptionAdd.as_view(), name="prescription-add"),
    path(
        "prescriptions/<int:pk>/",
        views.PrescriptionUpdate.as_view(),
        name="prescription-update",
    ),
    path(
        "prescriptions/<int:pk>/delete/",
        views.PrescriptionDelete.as_view(),
        name="prescription-delete",
    ),
    path(
        "supplies/<int:pk>/adjust/",
        views.SupplyItemAdjust.as_view(),
        name="supplyitem-adjust",
    ),
    path(
        "supplies/<int:pk>/open/",
        views.SupplyItemOpenPackage.as_view(),
        name="supplyitem-open",
    ),
    path(
        "supplies/count/",
        views.PhysicalCountEntry.as_view(),
        name="physical-count",
    ),
    path(
        "inventory/transactions/",
        views.InventoryTransactionList.as_view(),
        name="inventorytransaction-list",
    ),
]