# Generated by Django 2.0.5 on 2018-07-15 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("babybuddy", "0002_add_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="dashboard_refresh_rate",
            field=models.DurationField(
                blank=True,
                choices=[
                    (None, "disabled"),
                    (datetime.timedelta(0, 60), "1 min."),
                    (datetime.timedelta(0, 120), "2 min."),
                    (datetime.timedelta(0, 180), "3 min."),
                    (datetime.timedelta(0, 240), "4 min."),
                    (datetime.timedelta(0, 300), "5 min."),
                    (datetime.timedelta(0, 600), "10 min."),
                    (datetime.timedelta(0, 900), "15 min."),
                    (datetime.timedelta(0, 1800), "30 min."),
                ],
                default=datetime.timedelta(0, 60),
                help_text="This setting will only be used when a browser does not support refresh on focus.",
                null=True,
                verbose_name="Refresh rate",
            ),
        ),
    ]
