# Generated by Django 2.2 on 2019-04-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("babybuddy", "0003_add_refresh_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="language",
            field=models.CharField(
                choices=[], default="en", max_length=255, verbose_name="Language"
            ),
        ),
    ]
