# Generated by Django 3.0.2 on 2020-01-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("babybuddy", "0007_auto_20190607_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("sv", "Swedish"),
                    ("tr", "Turkish"),
                ],
                default="en",
                max_length=255,
                verbose_name="Language",
            ),
        ),
    ]
