# Generated by Django 3.1.5 on 2021-01-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("babybuddy", "0013_auto_20210411_1241"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="dashboard_hide_empty",
            field=models.BooleanField(
                default=False, verbose_name="Hide Empty Dashboard Cards"
            ),
        ),
    ]
