# Generated by Django 4.0.7 on 2022-08-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0023_alter_settings_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nap_start_min",
                    models.TimeField(
                        blank=True,
                        help_text="The minimum default time that a sleep entry is consider a nap.If set the nap property will be preselected if the starttime is within the bounds.",
                        null=True,
                        verbose_name="Default minimum nap start time",
                    ),
                ),
                (
                    "nap_start_max",
                    models.TimeField(
                        blank=True,
                        help_text="The maximum default time that a sleep entry is consider a nap.If set the nap property will be preselected if the starttime is within the bounds.",
                        null=True,
                        verbose_name="Default maximum nap start time",
                    ),
                ),
            ],
        ),
    ]
