# Generated by Django 4.1.2 on 2022-10-23 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("babybuddy", "0023_alter_settings_timezone"),
    ]

    # Migration removed in favor of post migrate handling in core.apps.CoreConfig.
    operations = []
