# Generated by Django 4.1.6 on 2023-02-09 03:36

from django.db import migrations
from django.contrib.auth.models import Group


def remove_standard_group(apps, schema_editor):
    Group.objects.filter(name="standard").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("babybuddy", "0026_alter_settings_timezone"),
    ]

    operations = [
        migrations.RunPython(remove_standard_group, migrations.RunPython.noop)
    ]
