# Generated by Django 4.2.3 on 2023-07-24 19:09

from django.db import migrations
from django.core.management import call_command


def create_cache_table(apps, schema_editor):
    call_command("createcachetable", verbosity=0)


class Migration(migrations.Migration):
    dependencies = [
        ("babybuddy", "0028_alter_settings_language_alter_settings_timezone"),
    ]

    operations = [migrations.RunPython(create_cache_table, migrations.RunPython.noop)]
