# Generated by Django 5.1 on 2024-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0033_alter_settings_dashboard_refresh_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="language",
            field=models.CharField(
                choices=[
                    ("pt-BR", "Brazilian Portuguese"),
                    ("ca", "Catalan"),
                    ("hr", "Croatian"),
                    ("cs", "Czech"),
                    ("zh-hans", "Chinese (simplified)"),
                    ("da", "Danish"),
                    ("nl", "Dutch"),
                    ("en-US", "English (US)"),
                    ("en-GB", "English (UK)"),
                    ("fr", "French"),
                    ("fi", "Finnish"),
                    ("de", "German"),
                    ("he", "Hebrew"),
                    ("hu", "Hungarian"),
                    ("it", "Italian"),
                    ("ja", "Japanese"),
                    ("nb", "Norwegian Bokmål"),
                    ("pl", "Polish"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("es", "Spanish"),
                    ("sv", "Swedish"),
                    ("tr", "Turkish"),
                    ("uk", "Ukrainian"),
                ],
                default="en-US",
                max_length=255,
                verbose_name="Language",
            ),
        ),
    ]
