# Generated by Django 5.1.6 on 2025-02-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0035_alter_settings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="display_feed_end_time",
            field=models.BooleanField(default=False, verbose_name="Display End Times"),
        ),
    ]
