# Generated by Django 5.2.17 on 2026-08-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0035_alter_settings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="dashboard_hidden_cards",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Cards which are not shown on child dashboards.",
                verbose_name="Hidden dashboard cards",
            ),
        ),
    ]
