# Generated by Django 5.1 on 2026-08-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("babybuddy", "0035_alter_settings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="hour_format",
            field=models.BooleanField(default=False, verbose_name="Use 24-hour format"),
        ),
    ]
