# Generated by Django 5.1.4 on 2025-01-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0036_alter_settings_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="feeding_end",
            field=models.BooleanField(
                default=False,
                help_text="Use feeding end instead of start time for displaying time between feedings",
                verbose_name="Use feeding end",
            ),
        ),
    ]
