#!/usr/bin/with-contenv bash
# shellcheck shell=bash

DEFAULT_CONF="/config/nginx/site-confs/default.conf"
OLD_ROOT="root /app/babybuddy/;"
NEW_ROOT="root /app/www/public;"

if [[ -f "${DEFAULT_CONF}" ]] && grep -q "${OLD_ROOT}" "${DEFAULT_CONF}" 2>/dev/null; then
  echo "updating root in ${DEFAULT_CONF}"
  sed -i "s|${OLD_ROOT}|${NEW_ROOT}|" "${DEFAULT_CONF}"
fi
