#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export \
  DJANGO_SETTINGS_MODULE="babybuddy.settings.base" \
  ALLOWED_HOSTS="${ALLOWED_HOSTS:-*}" \
  TIME_ZONE="${TZ:-UTC}" \
  DEBUG="${DEBUG:-False}" \
  SECRET_KEY="${SECRET_KEY:-$(cat /config/.secretkey)}"

exec \
  s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 3000" \
    cd /app/www/public s6-setuidgid abc gunicorn babybuddy.wsgi -b 127.0.0.1:3000 --log-level=info \
      --worker-tmp-dir=/dev/shm --log-file=- \
      --workers=2 --threads=4 --worker-class=gthread
